selected_country = "singapore"
selected_zone = "a"
instance_customizable_name = "machine"
ssh_public_key_path = "~/.ssh/my_ssh_key.pub"
domain_name = "example.com"
subdomain_name = "subdomain-name"
namecheap_ddns_password = "youShouldPassItOnTheFly"
trojan_go_password = "youShouldPassItOnTheFly"
