---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Wait for instance to be ready
      wait_for_connection:
        timeout: 300

    - name: Remove previous trojan-go-caddy Directory
      ansible.builtin.file:
        state: absent
        path: /opt/trojan-go-caddy/

    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/Jeonkwan/trojan-go-caddy.git'
        dest: /opt/trojan-go-caddy
        version: master
        clone: yes
      tags:
        - trojan

    - name: Create debug.log
      ansible.builtin.file:
        path: /opt/debug.log
        state: touch
      tags:
        - trojan

    - name: Update Namecheap Record
      become_user: root
      shell: |
        DOMAIN="{{ domain_name }}" \
        SUBDOMAIN="{{ subdomain_name }}" \
        INSTANCE_PUBLIC_IP="{{ public_ip }}" \
        NAMECHEAP_DDNS_PASS="{{ namecheap_ddns_password }}" \
        /usr/bin/bash /opt/trojan-go-caddy/configure_namecheap_dns.sh >> debug.log
      args:
        chdir: /opt/trojan-go-caddy
      tags:
        - trojan

    - name: Configure Trojan go
      become_user: root
      shell: |
        FULL_DOMAIN_NAME="{{ subdomain_name }}.{{ domain_name }}" \
        TROJAN_PASSWORD="{{ trojan_go_password }}" \
        /usr/bin/bash ./configure_trojan-go.sh >> debug.log
      args:
        chdir: /opt/trojan-go-caddy
      tags:
        - trojan

    - name: List content for debug
      shell: /usr/bin/tree ./ >> debug.log
      args:
        chdir: /opt/trojan-go-caddy
      tags:
        - trojan
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags: 
        - docker
  
    - name: Get Ubuntu Code Name
      ansible.builtin.shell: lsb_release -sc
      register: code_name_result

    - name: Add Docker Repository
      apt_repository:
        repo: "deb https://download.docker.com/linux/ubuntu {{ code_name_result.stdout }} stable"
        state: present
        update_cache: yes
      tags: 
        - docker

    - name: Install required system packages
      apt:
        pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
        - at
        - curl
        - uuid
        - zip
        - unzip
        - ipcalc
        state: latest
        update_cache: yes
        install_recommends: no

    - name: Add "ubuntu" user to "docker" group
      ansible.builtin.user:
        name: "{{ username }}"
        groups: 
          - docker
        append: yes
      tags:
        - docker

    # - name: Install docker-compose from official github repo
    #   get_url:
    #     url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    #     dest: /usr/local/bin/docker-compose
    #     mode: 'u+x,g+x'
    #   tags:
    #     - docker

    # - name: Create docker-compose symbolic link
    #   ansible.builtin.file:
    #     src: /usr/local/bin/docker-compose
    #     dest: /usr/bin/docker-compose
    #     group: docker
    #     state: link
    #   tags:
    #     - docker
    
    - name: Start and enable Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes
      tags:
        - docker

    # disable for ubuntu noble
    # - name: Install Python Docker Module for Ansible
    #   pip:
    #     name: 
    #       - docker
    #       - docker-compose
    #   tags:
    #     - docker

    - name: Trojan Go Down
      community.docker.docker_compose_v2:
        project_src: /opt/trojan-go-caddy
        files: 
          - docker-compose_trojan-go.yml
        state: absent
      tags:
        - trojan
        - docker-compose

    - name: Trojan Go Up
      community.docker.docker_compose_v2:
        project_src: /opt/trojan-go-caddy
        files: 
          - docker-compose_trojan-go.yml
        state: present
      tags:
        - trojan
        - docker-compose

    - name: Create daily reboot cronjob
      ansible.builtin.cron:
        name: "daily reboot"
        minute: "0"
        hour: "20"
        job: 'reboot'
        state: present
      tags:
        - cronjob
