---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Remove previous trojan-go-caddy Directory
      ansible.builtin.file:
        state: absent
        path: /opt/trojan-go-caddy/

    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/Jeonkwan/trojan-go-caddy.git'
        dest: /opt/trojan-go-caddy
        version: master
        clone: yes
      tags:
        - trojan

    - name: Update Namecheap Record
      become_user: root
      shell: |
        DOMAIN="{{ domain_name }}" \
        SUBDOMAIN="{{ subdomain_name }}" \
        INSTANCE_PUBLIC_IP="{{ public_ip }}" \
        NAMECHEAP_DDNS_PASS="{{ namecheap_ddns_password }}" \
        /usr/bin/bash /opt/trojan-go-caddy/configure_namecheap_dns.sh
      args:
        chdir: /opt/trojan-go-caddy
      tags:
        - trojan

    - name: Configure Trojan go
      become_user: root
      shell: |
        FULL_DOMAIN_NAME="{{ subdomain_name }}.{{ domain_name }}" \
        TROJAN_PASSWORD="{{ proxy_server_uuid }}" \
        /usr/bin/bash ./configure_trojan-go.sh
      args:
        chdir: /opt/trojan-go-caddy
      tags:
        - trojan

    - name: List content for debug
      shell: /usr/bin/tree ./
      args:
        chdir: /opt/trojan-go-caddy
      tags:
        - trojan

    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags:
        - docker

    - name: Get Ubuntu Code Name
      ansible.builtin.shell: lsb_release -sc
      register: code_name_result
      tags:
        - docker

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: "deb https://download.docker.com/linux/ubuntu {{ code_name_result.stdout }} stable"
        state: present
        update_cache: no
      tags:
        - docker

    - name: Install docker ce packages
      ansible.builtin.shell: |
        export DEBIAN_FRONTEND="noninteractive"
        apt-get -y update
        apt-get -y install --no-install-recommends \
          docker-ce \
          docker-ce-cli \
          containerd.io \
          docker-buildx-plugin \
          docker-compose-plugin
      register: apt_install_docker_ce
      tags:
        - docker

    - name: Add "ubuntu" user to "docker" group
      ansible.builtin.user:
        name: "{{ username }}"
        groups:
          - docker
        append: yes
      tags:
        - docker

    - name: Start and enable Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes
      tags:
        - docker

    - name: Trojan Go Down
      community.docker.docker_compose_v2:
        project_src: /opt/trojan-go-caddy
        files:
          - docker-compose_trojan-go.yml
        state: absent
      tags:
        - trojan
        - docker-compose

    - name: Trojan Go Up
      community.docker.docker_compose_v2:
        project_src: /opt/trojan-go-caddy
        files:
          - docker-compose_trojan-go.yml
        state: present
      tags:
        - trojan
        - docker-compose

    - name: Create daily reboot cronjob
      ansible.builtin.cron:
        name: "daily reboot"
        minute: "0"
        hour: "20"
        job: 'reboot'
        state: present
      tags:
        - cronjob
