name: Terraform Validate

on:
  pull_request:
    branches:
      - '**'

permissions:
  contents: read
  actions: write

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      TF_INPUT: "false"
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Configure Terraform plugin cache
        run: |
          echo "TF_PLUGIN_CACHE_DIR=$RUNNER_TEMP/.terraform.d/plugin-cache" >> "$GITHUB_ENV"
          mkdir -p "$RUNNER_TEMP/.terraform.d/plugin-cache"

      - name: Cache Terraform plugins
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/.terraform.d/plugin-cache
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - name: Note cache skip on forked pull requests
        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository
        run: |
          echo "Skipping cache restore/save because this pull request originates from a fork without cache permissions."

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
          terraform_wrapper: false

      - name: Terraform init
        run: terraform init -backend=false

      - name: Terraform validate
        run: terraform validate
